/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AuthClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "AuthUserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "MyIdentityPool": {
      "id": string
      "type": "sst.aws.CognitoIdentityPool"
    }
    "StarterAuthAPI": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "StarterFrontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
